version: "3"
services:
  elec_server:
    container_name: elec_server
    image: kellu001/elec_server
    restart: always
    build: .
    ports:
      - "3050:3050"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
